# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'first_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for first_ios

  target 'first_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'first_iosUITests' do
    # Pods for testing
  end

pod 'lottie-ios'

end
